/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      backgroundImage: {
        homeCharmander: "url('/charmander-home.png')",
        bgCharacters: "url('/bg-characters.png')",
        bgColeta: "url('/fondo-coleta.png')",
        puebloPaleta: "url('/fondo-permanente.png')",
        pikachuFondo: "url('/fondo-pikachu.png')",
        pixelFondo: "url('/fondoPixeleado.png')",
        bgPikachu: "url('/pikachu-bg.png')",
        bgPikachuHierba: "url('/pikachu-hierba.png')",
        bgPokemonesMitad: "url('/pokemons-mitad.png')",
        bgFondoMate: "url('/fondo-mate.png')",
        bgPokemonBatalla: "url('/batalla-pokemon-fondo.jpg')",
        bgPokemonVolando: "url('/bg-pokemon-volando.jpeg')",
        bgPokemonFondoNegro: "url('/bg-pokemon-negro-fondo.jpeg')",
        bgPokemonesUnidos: "url('/pokemon-unidos.jpeg')",
        bgPokemonNavidad: "url('/bg-pokemon-navidad.jpeg')",
        bgPokemonCiudad: "url('/bg-pokemon-ciudad.jpeg')",
        bgPokemonControlParental: "url('/fondo-control-parental.jpeg')",
        bgFondoMapaJuego: "url('/fondo-mapa.png')",
        bgFondoMapaJuego2: "url('/fondo-mapa2.png')",
        bgFondoMapaJuego3: "url('/bgSquirtleFondo.png')",
        bgFondoMapaJuego4: "url('/pokemon-unidos.png')",
        bgFondoMapaJuego5: "url('/pokemones-separados.png')",
        bgFondoMapaJuego6: "url('/nenufars-pokemon.png')",
        bgPokemonPregunta1: "url('/pokemon-pregunta-1.jpeg')",
        bgPokemonPregunta2: "url('/pokemon-pregunta-2.jpeg')",
        bgPokemonPregunta3: "url('/pokemon-pregunta-3.jpeg')",
        bgPokemonPregunta4: "url('/pokemon-pregunta-4.jpeg')",
        bgPokemonPregunta5: "url('/pokemon-pregunta-5.jpeg')",
        bgPokemonPregunta6: "url('/pokemon-pregunta-6.jpeg')",
        bgPokemonPregunta7: "url('/pokemon-pregunta-7.jpeg')",
        bgPokemonPregunta8: "url('/pokemon-pregunta-8.jpeg')",
        bgPokemonPregunta9: "url('/pokemon-pregunta-9.jpeg')",
        bgPokemonPregunta10: "url('/pokemon-pregunta-10.jpeg')",
        bgPokemonPregunta11: "url('/pokemon-pregunta-11.jpeg')",
      },
    },
    fontFamily: {
      LilitaOne: ["Lilita One"],
      PacificoFamily: ["Pacifico"],
      MarkerDisplay: ["Permanent Marker"],
    },
  },
  plugins: [],
};
